CREATE TABLE IF NOT EXISTS Projects
(
    project_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) UNIQUE NOT NULL,
    address    VARCHAR(50)         NOT NULL
);


CREATE TABLE IF NOT EXISTS Users
(
    user_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50)        NOT NULL,
    surname  VARCHAR(50)        NOT NULL,
    email    VARCHAR(50) UNIQUE NOT NULL,
    phone    VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100)       NOT NULL,
    role     VARCHAR(100)       NOT NULL
);


CREATE TABLE IF NOT EXISTS Users_Project
(
    user_id    INT,
    project_id INT,
    FOREIGN KEY (user_id) REFERENCES users (user_id),
    FOREIGN KEY (project_id) REFERENCES projects (project_id)
);

CREATE TABLE IF NOT EXISTS Orders
(
    order_id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR(50) NOT NULL,
    order_date                DATE        NOT NULL,
    requirement_delivery_date DATE        NOT NULL,
    estimated_delivery_date   DATE,
    actual_delivery_date      DATE,
    status                    VARCHAR(50),
    project_id                INT         NOT NULL,
    user_id                   INT         NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects (project_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);


CREATE TABLE IF NOT EXISTS Items
(
    item_id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR(50)   NOT NULL,
    unit_measurement          VARCHAR(25)   NOT NULL,
    amount                    DECIMAL(6, 2) NOT NULL,
    requirement_delivery_date DATE          NOT NULL,
    estimated_delivery_date   DATE,
    actual_delivery_date      DATE,
    notes                     VARCHAR(1000),
    order_id                  INT           NOT NULL,
    FOREIGN KEY (order_id) REFERENCES Orders (order_id)
);

CREATE TABLE IF NOT EXISTS Logs
(
    log_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change  DATE,
    status  VARCHAR(25),
    order_id INT,
        FOREIGN KEY (order_id) REFERENCES Orders (order_id)
);